---
- name: create stellar-core mount directory
  file:
    path: /opt/stellar-core/volumes/stellar-core
    state: directory
    mode: 0655

- name: create stellar-core scripts directory
  file:
    path: /opt/stellar-core/scripts
    state: directory
    mode: 0655

- name: template stellar-core.cfg
  template:
    src: stellar-core.cfg.j2
    dest: /opt/stellar-core/volumes/stellar-core/stellar-core.cfg
    mode: 0600

- name: template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/stellar-core/docker-compose.yml
    mode: 0644

- name: pull docker image - this tends to fail so ignore errors
  docker_service:
    project_src: /opt/stellar-core
    pull: yes
    state: present
    stopped: yes
  ignore_errors: yes

- name: pull docker image - again
  docker_service:
    project_src: /opt/stellar-core
    pull: yes
    state: present
    stopped: yes

- name: template init_core script to remote
  template:
    src: scripts/init_core.sh.j2
    dest: /opt/stellar-core/scripts/init_core.sh
    mode: 0700

- name: template upload_core_logs script to remote
  template:
    src: scripts/upload_core_logs.sh.j2
    dest: /opt/stellar-core/scripts/upload_core_logs.sh
    mode: 0700

- name: template upload_core_db script to remote
  template:
    src: scripts/upload_core_db.sh.j2
    dest: /opt/stellar-core/scripts/upload_core_db.sh
    mode: 0700

- name: template set_core_log_level script to remote
  template:
    src: scripts/set_core_log_level.sh.j2
    dest: /opt/stellar-core/scripts/set_core_log_level.sh
    mode: 0700

- name: start stellar-core-telegraf
  docker_service:
    project_src: /opt/stellar-core
    services:
      - stellar-core-telegraf
    state: present

- meta: end_play ## stops the play here ##

- name: initialize database
  command: docker-compose run --rm stellar-core --newdb
  args:
    chdir: /opt/stellar-core

- name: initialize scp
  command: docker-compose run --rm stellar-core --forcescp
  args:
    chdir: /opt/stellar-core

- name: initialize history archive
  command: docker-compose run --rm stellar-core --newhist my-bucket
  args:
    chdir: /opt/stellar-core

- name: start stellar-core
  docker_service:
    project_src: /opt/stellar-core


- name: configure core parameters
  uri:
    url: http://localhost:11626/upgrades?mode=set&upgradetime=1970-01-01T00:00:00Z&basereserve=0&maxtxsize=500&protocolversion=9'
    method: GET
